version: '3.9'

services:
  valkey:
    image: 'valkey/valkey:latest'
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: localhost_dev
    volumes:
      - ".docker/init/:/docker-entrypoint-initdb.d/"
  mongodb:
    image: 'mongo:latest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: localhost_dev
      MONGO_INITDB_ROOT_PASSWORD: localhost_dev_pwd
    ports:
      - 27017:27017
  vault:
    image: 'vault:1.13.3'
    restart: always
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      SKIP_CHOWN: true
    volumes:
      - .vault/config:/vault/config
      - .vault/file:/vault/file
      - .vault/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/local.json