spring:
  config:
    activate:
      on-profile: common-cache-dev
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.data.*.*: trace
    org.springframework.cache.*: trace
    root: INFO
    redis.clients: TRACE
    org.springframework.data: TRACE

