server:
  servlet:
    context-path: /auth
  port: 8090
spring:
  application:
    name: authenticate
  profiles:
    include:
#      - auth-entity-dev
      - auth-r2-entity-dev
      - common-cache-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: ${java.io.tmpdir}